### ISSUE TITLE
Model could not be applied in webUI

### ISSUE THREAD

**Issue by ghost** [wusongbai139/controlnet_TrainingPackage#3]
你好，我是用您的脚本训练出了Control net模型，非常感谢！但是训练出来后在webUI内不能用，具体表现为1：更换其他输入模型，输出基本一样；2训练其他模型，重复出现第一个问题。请问模型是要放在extension下controlnet\models里面吗？还是另有其他地方？

**Comment by wusongbai139** [comment]
放到extension\controlnet\models里即可。估计你的训练样本太少，导致没有效果。
